POST http://localhost:3333/register 
Content-Type: application/json

{
  "name": "Usuario jwt",
  "email": "emailteste55@email.com",
  "password": "SenhaSegura123",
  "cpf": "99345678904",
  "rg": "599.559-2",
  "gender": "M",
  "phoneNumber": "92345678900",
  "birthDate": "1980-01-01",
  "doctorName": "Veida Borges Soares de Queiroz",
  "uf": "SE",
  "crm": "7286",
  "especialidade": "Dermatologia",
  "diagnostico": "Dermatite Atópica",
  "cid": "L20.9"
}

###

GET http://localhost:3333/approve/9a22f90b-47d8-4b06-912e-8057c2a5e16c

# const doctarData: DoctorData = {
#   name: "Veida Borges Soares de Queiroz",
#   crm: 7286,
#   uf: "SE",
# };