POST http://localhost:3333/register 
Content-Type: application/json

{
  "name": "Segundo Fulano da silva",
  "email": "fulano2@email.com",
  "password": "SenhaSegura123",
  "cpf": "12345678901",
  "rg": "599.559-9",
  "gender": "M",
  "phoneNumber": "12345678900",
  "birthDate": "1980-01-01",
  "doctorName": "Veida Borges Soares de Queiroz",
  "uf": "SE",
  "crm": "7286",
  "especialidade": "Dermatologia",
  "diagnostico": "Dermatite Atópica",
  "cid": "L20.9"
}

###

GET http://localhost:3333/approve/05243cb3-ff78-4547-a6c1-f851753fb3e7

# const doctarData: DoctorData = {
#   name: "Veida Borges Soares de Queiroz",
#   crm: 7286,
#   uf: "SE",
# };